<div class="jarviswidget jarviswidget-sortable jarviswidget-color-white" data-widget-deletebutton='false' data-widget-editbutton='false' data-widget-colorbutton='false'>
<header>
  <span class="widget-icon"><i class="fa fa-list"></i></span>
  <h2>List of all currency objects</h2>
</header>
<!-- widget div-->
<div>
<!-- widget content -->
  <div class="widget-body no-padding">
    <div class="widget-body-toolbar"></div>
  <!-- widget content -->
      <TABLE id="dt_basic" class="table table-striped table-bordered table-hover dataTable">
          <THEAD>
            <TR>
              <TH>ID</TH>
              <TH>name</TH>
              <TH>symbol</TH>
              <TH>details</TH>
              <TH>modify</TH>
              <!-- <TH>delete</TH> -->
            </TR>
          </THEAD>
          <TBODY>
<?php
/* @var $item Admin\Model\Language */
foreach($this->paginator as $item)
{
?>
<TR>
    <TD class='admin c'><?=$item->id?></TD>

    <TD class='admin'><?=$item->name?></TD>
    <TD class='admin'><?=$item->symbol?></TD>
    <TD class='admin c'>
    <a title='details' class='btn blue btn-default btn-sm' href='/admin/currency/detail/id/<?=$item->id?>'><i class='fa fa-icon-fix fa-info'></i></a>
    </TD>
    <TD class='admin c'>
    <a title='Modify currency object' href='/admin/currency/modify/id/<?=$item->id?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
    </TD>
    <!-- <TD class='admin c'>
    <a id='delete_<?=$item->id?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
    <div style='display: none' id='delete_delete_<?=$item->id?>' class='dialog_hide'>
        <p>Are you sure you would like to delete this currency?</p>
        <ul>
          <li><a class='btn btn-danger' href='/admin/currency/delete/id/<?=$item->id?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
          <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
        </ul>
    </div>
    </TD> -->
    </TR>
<?php
}
?>
          </TBODY>
        </TABLE>
  </div>
  <!-- end widget content -->
</div>
</div>