<section>
    <p>
        <a href="/admin/user" class="btn btn-default">
            <i class="fa fa-chevron-left"></i>&nbsp;<?=$this->session->BACK?>
        </a>
    </p>
    <div class='table-style'>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->NAME?></li>
            <li class="table-cell"><?=$this->user->getName()."&nbsp;".$this->user->getSurname()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->USERNAME?></li>
            <li class="table-cell"><?=$this->user->getUsername()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->EMAIL?></li>
            <li class="table-cell"><?=$this->user->getEmail()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->LAST_LOGIN?></li>
            <li class="table-cell"><?=$this->user->getLastLogin()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->DISABLED?></li>
            <li class="table-cell"><? if ($this->user->getDeleted()) { ?> <i class='fa fa-check'></i> <? } else {  ?> <i class='fa fa-times'></i> <?}?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->BAN?></li>
            <li class="table-cell"><? if ($this->user->getBan()) { ?> <i class='fa fa-check'></i> <? } else {  ?> <i class='fa fa-times'></i> <?}?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->REGISTERED?></li>
            <li class="table-cell"><?=$this->user->getRegistered()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->USER_CLASSES?></li>
            <li class="table-cell"><?=$this->user->getUserClassNames()?></li>
        </ul>
    </div>
</section>