<?php
if (count($this->contents) > 0) {
    $c = $this->contents->current();
    echo "<h2 itemscope itemprop='name'>{$c->getTitle()}</h2>";

    if($c->getPreview() != null) {
?>
        <figure itemscope itemtype="http://schema.org/ImageObject" class="image-size">
            <a itemprop="url" href="/userfiles/preview/<?=$c->getPreview();?>" id="news_image" title="<?=$c->getTitle();?>">
                <img itemprop="image" src="/userfiles/preview/<?=$c->getPreview();?>" title="<?=$c->getTitle();?>" alt="<?=$c->getTitle();?>" />
            </a>
        </figure>
<?php
    }
    echo "<p itemscope itemprop='text' class='post-text'>{$c->getText()}</p>";
} else {
    echo "<h3 class='c no-content'>{$this->translation->NO_CONTENT}</h3>";
}
?>