<?php
if(count($this->news) > 0) {
    foreach($this->news as $new) {
        $dateTime = date("Y-m-d", strtotime($new->getDate()));
        $dateTimeShow = date("M d, Y", strtotime($new->getDate()));
?>
            <article class="post-content" itemscope itemprop="event" itemtype="http://schema.org/Article">
<?php
                if ($new->getPreview() != null) { ?>
                    <figure itemscope itemtype="http://schema.org/ImageObject" class="image-size">
                        <a itemprop="url" href="/userfiles/preview/<?=$new->getPreview();?>" id="news_image" title="<?=$new->getTitle();?>">
                            <img itemprop="image" src="/userfiles/preview/<?=$new->getPreview();?>" title="<?=$new->getTitle()?>" alt="<?=$new->getTitle();?>" />
                        </a>
                    </figure>
<?php           } ?>

                <h2 itemscope itemprop="name" class="post-title">
                    <a itemprop="url" href="/news/post/<?=$new->getTitleLink()?>"><?=$new->getTitle()?></a>
                </h2>

                <time datetime="<?=$dateTime?>" class="post-date">
                    <?=$this->translation->POSTED_ON?>&nbsp;<meta itemprop="datePublished" content="<?=$dateTime?>"><?=$dateTimeShow?>
                </time>

                <p itemscope itemprop="text" class="post-text"><?=substr(strip_tags($new->getText()), 0, 300)."...";?></p>
                <br>
<?php           if (mb_strlen($new->getText()) > 0) { ?>
                    <p><a itemscope itemprop="url" title="<?=$this->translation->READ_MORE?>" class="read-more" href="<?=$this->url('news', array('post' => $new->getTitleLink()));?>"><?=$this->translation->READ_MORE?></a></p>
<?php       } ?>
            </article>
<?php
    }
    echo $this->paginationControl($this->news, 'sliding', array('/application/pagination.phtml', "Application"), array('route' => 'news'));
} elseif(count($this->new) === 1 && !$this->news) {
    $dateTime = date("Y-m-d", strtotime($this->new->getDate()));
    $dateTimeShow = date("M d, Y", strtotime($this->new->getDate()));
?>
    <article class="post-content" itemscope itemprop="event" itemtype="http://schema.org/Article">
        <h2 itemprop="name" class="post-title"><?=$this->new->getTitle();?></h2>

        <?php if ($this->new->getPreview() != null) { ?>
            <figure itemscope itemtype="http://schema.org/ImageObject" class="image-size">
                <a itemprop="url" href="/userfiles/preview/<?=$this->new->getPreview();?>" id="news_image" title="<?=$this->new->getTitle();?>">
                    <img itemprop="image" src="/userfiles/preview/<?=$this->new->getPreview();?>" title="<?=$this->new->getTitle();?>" alt="<?=$this->new->getTitle();?>" />
                </a>
            </figure>
        <?php } ?>

        <time datetime="<?=$dateTime?>" class="post-date">
            <?=$this->translation->POSTED_ON?>&nbsp;<meta itemprop="datePublished" content="<?=$dateTime?>"><?=$dateTimeShow;?>
        </time>

        <div itemprop="text" class="post-text"><?=$this->new->getText();?></div>
        <p><a itemprop="url" href="<?=$this->url('news');?>" title="<?=$this->translation->BACK_TO_NEWS_OVERVIEW;?>" class="read-more"><?=$this->translation->BACK_TO_NEWS_OVERVIEW;?></a></p>
    </article>
<?php
} else {
    echo "<h3 itemscope itemprop='name' class='c no-content'>".$this->translation->NO_CONTENT."</h3>";
}
?>