filter:
    excluded_paths:
        - 'vendor/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            general:
                linefeed_character: newline
            around_operators:
                equality: false
                concatenation: false
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: undefined
            for:
                opening: undefined
            while:
                opening: undefined
            do_while:
                opening: undefined
            switch:
                opening: undefined
            try:
                opening: undefined
        upper_lower_casing:
            keywords:
                general: undefined
            constants:
                true_false_null: undefined
build: true
