<div class="jarviswidget jarviswidget-sortable jarviswidget-color-white" data-widget-deletebutton='false' data-widget-editbutton='false' data-widget-colorbutton='false'>
<header>
  <span class="widget-icon"><i class="fa fa-list"></i></span>
  <h2>List of all menu objects</h2>
</header>
<!-- widget div-->
<div>
<!-- widget content -->
  <div class="widget-body no-padding">
    <div class="widget-body-toolbar"></div>
  <!-- widget content -->
      <table id="dt_basic" class="table table-striped table-bordered table-hover">
          <THEAD>
            <TR>
              <TH>caption</TH>
              <TH>order</TH>
              <TH>keywords</TH>
              <TH>description</TH>
              <TH>details</TH>
              <th>menutype</th>
              <TH>modify</TH>
              <TH>delete</TH>
            </TR>
          </THEAD>
          <TBODY>
<?php
/* @var $menu Admin\Model\Menu */
if (!empty($this->menus)) {
foreach($this->menus as $key => $menu)
{
    $menu->setServiceLocator(null);
?>
<TR>
    <TD class='admin'><?=$menu->getCaption()?></TD>
    <TD class='admin'><?=$menu->getMenuOrder()?></TD>
    <TD class='admin'><?=$menu->getKeywords()?></TD>
    <TD class='admin'><?=$menu->getDescription()?></TD>
    <TD class='admin c'>
      <a title='Menu details' href='/admin/menu/detail/id/<?=$menu->getId()?>' class='btn btn-default btn-sm blue'><i class='fa fa-icon-fix fa-info'></i></a>
    </TD>
    <TD class='admin'><?=$menu->getMenuTypeAsName()?></TD>
    <TD class='admin c'>
    <a title='Modify menu object' href='/admin/menu/modify/id/<?=$menu->getId()?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
    </TD>
    <TD class='admin c'>
    <a id='delete_<?=$menu->getId()?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
    <div style='display: none' id='delete_delete_<?=$menu->getId()?>' class='dialog_hide'>
        <p>Are you sure you would like to delete this menu?</p>
        <ul>
          <li><a class='btn btn-danger' href='/admin/menu/delete/id/<?=$menu->getId()?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
          <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
        </ul>
    </div>
    </TD>
    </TR>
<?php
    if(!empty($this->submenus[$key]))
    {
        foreach($this->submenus[$key] as $sub)
        {
            $sub->setServiceLocator(null);
?>
            <TR>
                <TD class='admin'><?=$sub->getCaption()?></TD>
                <TD class='admin'><?=$sub->getMenuOrder()?></TD>
                <TD class='admin'><?=$sub->getKeywords()?></TD>
                <TD class='admin'><?=$sub->getDescription()?></TD>
                <TD class='admin c'>
                <a title='Menu details' href='/admin/menu/detail/id/<?=$sub->getId()?>' class='btn btn-default btn-sm blue'><i class='fa fa-icon-fix fa-info'></i></a>
                </TD>
                <TD class='admin'><?=$sub->getMenuTypeAsName()?></TD>
                <TD class='admin c'>
                <a title='Modify menu object' href='/admin/menu/modify/id/<?=$sub->getId()?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
                </TD>
                <TD class='admin c'>
                <a id='delete_<?=$sub->getId()?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
                <div style='display: none' id='delete_delete_<?=$sub->getId()?>' class='dialog_hide'>
                    <p>Are you sure you would like to delete this menu?</p>
                    <ul>
                      <li><a class='btn btn-danger' href='/admin/menu/delete/id/<?=$sub->getId()?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
                      <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
                    </ul>
                </div>
                </TD>
                </TR>
<?php
        }
    }
}
}
?>
          </TBODY>
        </TABLE>
  </div>
  <!-- end widget content -->
</div>
</div>