<div class="jarviswidget jarviswidget-sortable jarviswidget-color-white" data-widget-deletebutton='false' data-widget-editbutton='false' data-widget-colorbutton='false'>
    <a href="/admin/menu" class="btn btn-labeled btn-default">
        <span class="btn-label"><i class="fa fa-chevron-left"></i></span>back to the list of menus
    </a>
    <br/><br/>
    <header>
        <span class="widget-icon"><i class="fa fa-list"></i></span>
        <h2>Modify menu</h2>
    </header>
    <div class='well'>
    <?php
    // First, set the action on the form
    $form = $this->form;
    $form->setAttribute('action', $this->url('admin',array('controller' =>'menu','action' => 'modify','id' => $this->id)));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
    </div>
</div>