<div>
<section>
    <div class="table-style">
        <ul class="table-header">
            <li class="table-cell"><?=$this->translate("NAME");?></li>
			<li class="table-cell"><?=$this->translate("MODIFY");?></li>
            <li class="table-cell"><?=$this->translate("DELETE");?></li>
        </ul>
<?php
       /**
        * @var $term Admin\Model\Tern
        */
        foreach($this->paginator as $term) {
?>
        <ul>
            <li class="table-cell"><?=$term->getName()?></li>
            <li class="table-cell">
                <a title='<?=$this->translate("DETAILS");?>' href='<?=$this->url("admin", ['controller' => "term", "action" => "modify", "id" => $term->getId()])?>' class='btn btn-sm orange'><i class='fa fa-pencil'></i></a>
            </li>
            <li class="table-cell">
                <button id='delete_<?=$term->getId()?>' type="button" class='btn btn-sm delete dialog_delete' title='<?=$this->translate("DELETE");?>'><i class='fa fa-trash-o'></i></button>
                <div id='delete_delete_<?=$term->getId()?>' class='dialog_hide'>
                    <p><?=$this->translate("DELETE_CONFIRM_TEXT");?> &laquo;<?=$term->getName()?>&raquo;</p>
                    <ul>
                        <li>
                            <a class='btn delete' href='<?=$this->url("admin", ['controller' => "term", "action" => "delete", "id" => $term->getId()])?>'><i class='fa fa-trash-o'></i> <?=$this->translate("DELETE");?></a>
                        </li>
                        <li>
                            <a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp;<?=$this->translate("CANCEL");?></a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
<?php
        }
    echo $this->paginationControl($this->paginator, 'sliding', 'admin/pagination', ['route' => 'admin']);
?>
    </div>
</section>