<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>

<dl>
    <!-- <p class='b'><?php echo $this->translate('File') ?>:</>
    <dd>
        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd> -->
<!--     <p class='b'><?php echo $this->translate('Message') ?>:</p> -->
    <dd>
        <div class='msg fail'><?php echo $this->escapeHtml($this->exception->getMessage()) ?></div>
    </dd>
</dl>

<?php endif ?>

<?php endif ?>
