<?php
/**
 * modified url representation to include any additional URL parameters in non-zend style
* @param unknown $replace
*/
$urlParams = array();
foreach ($this->params()->fromPost() as $urlParamsKey=>$urlParamsVal)
{
    if (!in_array($urlParamsKey, array('module', 'controller', 'action', 'page', 'submit')))
    {
        $urlParams[$urlParamsKey] = $urlParamsVal;
    }
}
?>

<div class="dt-row dt-bottom-row">
  <div class="row">
    <div class="col-sm-6">
      <div class="dataTables_info" id="dt_basic_info">Showing <?= $this->current; ?> of <?= $this->last; ?> pages</div>
    </div>
    <div class="col-sm-6 text-right">
      <div class="dataTables_paginate paging_bootstrap_full">
        <ul class="pagination">
          <?php if (isset($this->previous)): ?>
          <li class="first">
            <a href="<?=$this->url($this->route, array_merge(array('page' => $this->first),$urlParams), false, true); ?>">First</a>
          </li>
          <?php else: ?>
          <li class="first disabled">
            <a href="#">First</a>
          </li>
          <?php endif; ?>
          <?php if (isset($this->previous)): ?>
          <li class="prev">
            <a href="<?=$this->url($this->route, array_merge(array('page' => $this->previous),$urlParams), false, true); ?>">Previous</a>
          </li>
          <?php else: ?>
          <li class="prev disabled">
            <a href="#">Previous</a>
          </li>
          <?php endif; ?>
          <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
            <li><a href="<?=$this->url($this->route, array_merge(array('page' => $page),$urlParams), false, true); ?>"><?= $page; ?></a></li>
            <?php else: ?>
            <li  class="active"><a href="<?=$this->url($this->route, array_merge(array('page' => $page),$urlParams), false, true); ?>"><?= $page; ?></a></li>
           <?php endif; ?>
          <?php endforeach; ?>
          <!-- Next page link -->
          <?php if (isset($this->next)): ?>
          <li class="next">
            <a href="<?=$this->url($this->route, array_merge(array('page' => $this->next), $urlParams), false, true); ?>">Next</a>
          </li>
          <?php else: ?>
          <li class="next disabled"><a href="#">Next</a></li>
          <?php endif; ?>
          <?php if (isset($this->next)): ?>
          <li class="last">
            <a href="<?=$this->url($this->route, array_merge(array('page' => $this->last),$urlParams), false, true); ?>">Last</a>
          </li>
          <?php else: ?>
          <li class="last disabled"><a href="#">Last</a></li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  </div>
</div>