<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                            => __DIR__ . '/Module.php',
    'Application\Controller\ErrorHandling'          => __DIR__ . '/src/Application/Controller/ErrorHandling.php',
    'Application\Controller\IndexController'        => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\LoginController'        => __DIR__ . '/src/Application/Controller/LoginController.php',
    'Application\Controller\MenuController'         => __DIR__ . '/src/Application/Controller/MenuController.php',
    'Application\Controller\NewsController'         => __DIR__ . '/src/Application/Controller/NewsController.php',
    'Application\Controller\ProfileController'      => __DIR__ . '/src/Application/Controller/ProfileController.php',
    'Application\Controller\RegistrationController' => __DIR__ . '/src/Application/Controller/RegistrationController.php',
    'Application\Controller\ShopController'         => __DIR__ . '/src/Application/Controller/ShopController.php',
    'Application\Factory\AdapterServiceFactory'     => __DIR__ . '/src/Application/Factory/AdapterServiceFactory.php',
    'Application\Form\ContactForm'                  => __DIR__ . '/src/Application/Form/ContactForm.php',
    'Application\Form\LoginForm'                    => __DIR__ . '/src/Application/Form/LoginForm.php',
    'Application\Form\NewPasswordForm'              => __DIR__ . '/src/Application/Form/NewPasswordForm.php',
    'Application\Form\RegistrationForm'             => __DIR__ . '/src/Application/Form/RegistrationForm.php',
    'Application\Form\ResetPasswordForm'            => __DIR__ . '/src/Application/Form/ResetPasswordForm.php',
    'Application\Form\UserSettingsForm'             => __DIR__ . '/src/Application/Form/UserSettingsForm.php',
    'Application\Model\ResetPassword'               => __DIR__ . '/src/Application/Model/ResetPassword.php',
    'Application\Model\ResetPasswordTable'          => __DIR__ . '/src/Application/Model/ResetPasswordTable.php',
    'Application\View\Helper\Params'                => __DIR__ . '/src/Application/View/Helper/Params.php',
);
