<section>
    <p>
        <a href="/admin/administrator" class="btn btn-default">
            <i class="fa fa-chevron-left"></i>&nbsp;<?=$this->session->BACK?>
        </a>
    </p>
    <div class='table-style'>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->NAME?></li>
            <li class="table-cell"><?=$this->administrator->toString()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->JOB?></li>
            <li class="table-cell"><?=$this->administrator->getJob()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->DESCRIPTION?></li>
            <li class="table-cell"><?=$this->administrator->getDescription()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->IMAGE?></li>
            <li class="table-cell"><img src="/adminfiles/<?=$this->administrator->name?>/images/<?=$this->administrator->getImage()?>" alt=""></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->DEPARTMENT?></li>
            <li class="table-cell"><?=$this->administrator->getDepartment()?></li>
        </ul>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->USER?></li>
            <li class="table-cell"><a href="/admin/user/detail/id/<?=$this->userObject->id?>"><?=$this->userObject->toString()?></a></li>
        </ul>
        </ul>
    </div>
</section>