<div>
<section>
    <div class="table-style">
        <ul class="table-header">
            <li class="table-cell"><?=$this->translation->NAME?></li>
            <li class="table-cell"><?=$this->translation->JOB?></li>
            <li class="table-cell"><?=$this->translation->DESCRIPTION?></li>
            <li class="table-cell"><?=$this->translation->DETAILS?></li>
            <li class="table-cell"><?=$this->translation->MODIFY?></li>
            <li class="table-cell"><?=$this->translation->DELETE?></li>
        </ul>
<?php
/* @var $item Admin\Model\Administrator */
foreach($this->paginator as $item)
{
?>
        <ul class="table-row">
            <li class="table-cell">
                <a title='<?=$this->translation->DETAILS?>' class='btn blue btn-sm' href='/admin/user/detail/id/<?=$item->getUser()?>'><?=$item->getUserObject()->getName()?> <i class='fa fa-info'></i></a>
            </li>
            <li class="table-cell">
                <a title='<?=$this->translation->MODIFY?>' href='/admin/administrator/modify/id/<?=$item->user?>' class='btn btn-sm orange'><i class='fa fa-pencil'></i></a>
            </li>
            <li class="table-cell">
                <a title='<?=$this->translation->DELETE?>' id='delete_<?=$item->user?>' href='#' class='btn btn-sm delete dialog_delete'><i class='fa fa-trash-o'></i></a>
                <div id='delete_delete_<?=$item->user?>' class='dialog_hide'>
                    <p><?=$this->translation->DELETE_CONFIRM_TEXT?>&nbsp;&laquo;<?=$item->getUserObject()->getName()?>&raquo;&quest;</p>
                    <ul>
                      <li><a class='btn delete' href='/admin/administrator/delete/id/<?=$item->user?>'><i class='fa fa-trash-o'></i>&nbsp;<?=$this->translation->DELETE?></a></li>
                      <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp;<?=$this->translation->CANCEL?></a></li>
                    </ul>
                </div>
            </li>
        </ul>
<?php
}
?>
    </div>
</section>
<?php
echo $this->paginationControl($this->paginator, 'sliding', '/admin/pagination.phtml', array('route' => 'admin'));
?>
</div>