<div class="showLogin" id="showForm">
  <p itemprop='name' class="legend"><?=$this->translation->LOGIN?></p>
<?php
$form = $this->form;
$form->setAttribute('action', '/login/processlogin');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
<p class="c"><a itemprop="url" href="/login/resetpassword"><?=$this->translation->RESET_PW?></a></p>
</div>