<?php
    $view = $this->viewModel()->getCurrent()->getChildren()[0];
?>
<!doctype html>
<html prefix="og: http://ogp.me/ns#" lang="<?=$view->langName?>">
    <head>
        <meta charset="utf-8">
        <title><?=$this->headTitle()->renderTitle();?></title>
        <?=$this->headMeta()?>

        <meta property="og:type" content="article">
        <meta property="og:url" content="<?=$view->baseURL?>">
        <meta property="og:site_name" content="<?=$this->headTitle()->renderTitle()?>">
        <meta name="author" content="Stanimir Dimitrov - stanimirdim92 at gmail dot com">
        <link rel="canonical" href="<?=$view->baseURL?>">
        <!-- <meta name="robots" content="index, follow" /> -->
        <!-- <meta name="Googlebot" content="index, follow" /> -->
        <!-- <meta name="revisit-after" content="3 Days" /> -->
        <?=$this->placeholder('customHead');?>
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        <meta http-equiv="cleartype" content="on">
        <link rel="apple-touch-icon" href="/front/img/apple-touch-icon.png">
        <link rel='shortcut icon' type="image/x-icon"  href='favicon.ico' />
        <link rel="icon" type="image/png" href="/favicon-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
        <meta name="msapplication-TileColor" content="#ededed">
        <meta name="msapplication-TileImage" content="/mstile-144x144.png">
        <link rel="stylesheet" media="screen" href="/front/css/font-awesome.min.css">

        <!-- TODO: add css  -->
        <link rel="stylesheet" media="screen" href="/front/css/style.css">
    </head>
    <body>
            <nav>
                <ul>
                <li><a href="&sol;"><?=$view->translation->HOME?></a></li>
<?php
            foreach($view->menus as $key => $menu)
            {
?>
                <li><a itemprop='url' href='<?=$this->url('menu', array('title' => $menu->getMenuLink()))?>'><?=$menu->getCaption();?></a>

<?php
                if(isset($view->submenus[$menu->id]) && count($view->submenus[$menu->id])>0)
                {
?>
                    <ul class="sub-menu">
<?php
                    foreach($view->submenus[$menu->id] as $sub)
                    {
?>
                        <li><a itemprop='url' href='<?=$this->url('menu', array('title' => $sub->getMenuLink()));?>'><?=$sub->getCaption();?></a></li>
<?php
                    }
?>
                    </ul>
<?php
                }
                echo "</li>";
            }
            echo "<li><a itemprop='url' href='&sol;login'>{$view->translation->LOGIN}</a></li>";
            echo $this->layout()->content;

            if(!empty($view->cache->warning))
            {
                if (is_array($view->cache->warning))
                {
                    foreach ($view->cache->warning as $warning)
                    {
?>
                  <div class="alert alert-warning">
                    <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
                    <i class="fa-fw fa fa-warning"></i> <?=$warning;?>
                  </div>
<?php
                    }
                }
                else
                {
?>
                  <div class="alert alert-warning">
                    <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
                    <i class="fa-fw fa fa-warning"></i> <?=$view->cache->warning;?>
                  </div>
<?php
                }
                $view->cache->warning = null;
            }

            if(!empty($view->cache->success))
            {
                if (is_array($view->cache->success))
                {
                    foreach ($view->cache->success as $success)
                    {
?>
                  <div class="alert alert-success">
                    <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
                    <i class="fa-fw fa fa-check"></i> <?=$success;?>
                  </div>
<?php
                    }
                }
                else
                {
?>
                  <div class="alert alert-success">
                    <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
                    <i class="fa-fw fa fa-check"></i> <?=$view->cache->success;?>
                  </div>
<?php
                }
                $view->cache->success = null;
            }

            if(!empty($view->cache->error))
            {
                if (is_array($view->cache->error))
                {
                    foreach ($view->cache->error as $error)
                    {
?>
                  <div class="alert alert-danger">
                    <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
                    <i class="fa-fw fa fa-times"></i> <?=$error;?>
                  </div>
<?php
                    }
                }
                else
                {
?>
                  <div class="alert alert-danger">
                    <button class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
                    <i class="fa-fw fa fa-times"></i> <?=$view->cache->error;?>
                  </div>
<?php
                }
                $view->cache->error = null;
            }
?>
        <!-- Load jQuery async, but defer all other scripts -->
        <script async src="/front/js/jquery.min.js"></script>
        <script defer src="/front/js/custom.js"></script>
    </body>
</html>