<?php
if ($this->viewModel()->getCurrent()->getChildren() != null) {
    $view = $this->viewModel()->getCurrent()->getChildren()[0];
?>
<!doctype html>
<html prefix="og: http://ogp.me/ns#" lang="">
    <head>
        <meta charset="utf-8">
        <title><?=$this->escapeHtml($this->headTitle()->renderTitle());?></title>
        <?php
            echo $this->headMeta();
            echo $this->placeholder('customHead');
            echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/favicon.ico'])
                ->prependStylesheet($this->basePath('/front/css/style.css'), 'screen')
                ->prependStylesheet($this->basePath('/front/css/font-awesome.min.css'), 'screen');
        ?>
        <meta property="og:site_name" content="<?=$this->escapeHtml($this->headTitle()->renderTitle());?>">
        <link rel="apple-touch-icon" href="<?=$this->basePath('/front/img/apple-touch-icon.png');?>">
        <link rel="canonical" href="<?=$this->serverUrl(true);?>">
        <link rel="shortlink" href="<?=$this->serverUrl(true);?>">
    </head>
    <body itemscope itemtype="http://schema.org/WebPage">
        <header id="header" role="banner">
            <nav id="nav" role="navigation">
                <ul>
                    <li><a itemprop='url' href="&sol;"><?=$this->translate("HOME");?></a></li>
<?php
                    if (!empty($view->menus)) {
                        foreach ($view->menus as $key => $menu) {
                            echo "<li><a itemprop='url' href='".$this->url('application/default', ['controller' => 'menu', 'action' => 'title', 'title' => $this->escapeHtml($menu->getMenuLink())])."'>".$menu->getCaption()."</a>";
                            if (!empty($view->submenus[$key])) {
                                echo "<ul class='sub-menu'>";
                                    foreach ($view->submenus[$key] as $sub) {
                                        echo "<li><a itemprop='url' href='".$this->url('application/default', ['controller' => 'menu', 'action' => 'title', 'title' => $this->escapeHtml($sub->getMenuLink())])."'>".$sub->getCaption()."</a></li>";
                                    }
                                echo "</ul>";
                            }
                            echo "</li>";
                        }
                    }
                    if (isset($view->identity) &&
                        $view->identity instanceof \stdClass &&
                        isset($view->identity->logged) &&
                        $view->identity->logged === true &&
                        in_array($view->identity->role, [10, 1])
                        ) {
?>
                    <li><a itemprop='url' href='<?=$this->url('application/default', ['controller' => 'login', 'action' => 'logout'])?>'><?=$this->translate("SIGN_OUT");?></a></li>
<?php
                    } else {
?>
                    <li><a itemprop='url' href='<?=$this->url('application/default', ['controller' => 'login'])?>'><?=$this->translate("SIGN_IN");?></a></li>
<?php
                    }
?>
                    <li><a itemprop='url' href='<?=$this->url('application/default', ['controller' => 'news'])?>'><?=$this->translate("NEWS");?></a></li>
                </ul>
            </nav>
        </header>
<?php
        /**
         * All messages passed from $this->setLayoutMessages() plugin method are showed with this code
         */
        if ($this->layout()->flashMessages) {
            foreach ($this->layout()->flashMessages->getCurrentMessages() as $context => $message) {
                echo '<div class="alert alert-' . $this->layout()->flashMessages->getNamespace() . '">
                        <ul>
                            <li>
                                <i class="fa-fw fa fa-'.$this->layout()->flashMessages->getNamespace().'"></i>' . $message . '
                                <button type="button" class="close"><i class="fa fa-times"></i></button>
                            </li>
                        </ul>
                      </div>
                ';
            }
        }
?>
    <div id="content-wrapper">
        <main id="main" role="main">
<?php
            /**
             * Every other html element must come from content variable
             * or in other simple words: Do not put any other html element around this code!
             */
            echo $this->layout()->content;
?>
        </main>
    </div>

    <aside role="complementary">

    </aside>

    <footer role="contentinfo">
        <small>Copyright &copy; <time datetime="<?=date("Y");?>"><?=date("Y");?></time></small>
    </footer>
<?php
        echo $this->headScript()
            ->prependFile($this->basePath('/front/js/custom.js'))
            ->prependFile($this->basePath('/front/js/jquery.min.js'));
?>
    </body>
</html>
<?php
}
