<section>
    <div class="table-style">
        <ul class="table-header">
            <li class="table-cell"><?=$this->session->NAME?></li>
            <li class="table-cell"><?=$this->session->MODIFY?></li>
            <li class="table-cell"><?=$this->session->DELETE?></li>
        </ul>
        <?php
        foreach($this->paginator as $item)
        {
        ?>
            <ul class="table-row">
                <li class="table-cell"><?=$item->getName()?></li>
                <li class="table-cell"><a title='<?=$this->session->MODIFY?>' href='/admin/termcategory/modify/id/<?=$item->id?>' class='btn btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a></li>
                <li class="table-cell">
                <a id='delete_<?=$item->id?>' href='#' class='btn btn-sm delete dialog_delete' title='<?=$this->session->DELETE?>'><i class='fa fa-icon-fix fa-trash-o'></i></a>
                <div id='delete_delete_<?=$item->id?>' class='dialog_hide'>
                    <p><?=$this->session->DELETE_CONFIRM_TEXT?>&nbsp;&laquo;<?=$item->getName()?>&raquo;&quest;</p>
                    <ul>
                        <li><a class='btn delete' href='/admin/termcategory/delete/id/<?=$item->id?>'><i class='fa fa-trash-o'></i>&nbsp;<?=$this->session->DELETE?></a></li>
                        <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp;<?=$this->session->CANCEL?></a></li>
                    </ul>
                </div>
                </li>
            </ul>
        <?
        }
        ?>
    </div>
</section>