<section>
    <div class="table-style">
        <ul class="table-header">
            <li class="table-cell"><?=$this->translate("NAME");?></li>
            <li class="table-cell"><?=$this->translate("MODIFY");?></li>
            <li class="table-cell"><?=$this->translate("DELETE");?></li>
        </ul>
<?php
       /**
        * @var $termcategory Admin\Model\TermCategory
        */
        foreach($this->paginator as $termcategory) {
?>
            <ul class="table-row">
                <li class="table-cell"><?=$termcategory->getName()?></li>
                <li class="table-cell">
                    <a title='<?=$this->translate("MODIFY");?>' href='<?=$this->url("admin", ['controller' => "termcategory", "action" => "modify", "id" => $termcategory->getId()])?>' class='btn btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
                </li>
                <li class="table-cell">
                    <button id='delete_<?=$termcategory->getId()?>' type="button" class='btn btn-sm delete dialog_delete' title='<?=$this->translate("DELETE");?>'><i class='fa fa-icon-fix fa-trash-o'></i></button>
                    <div id='delete_delete_<?=$termcategory->getId()?>' class='dialog_hide'>
                        <p><?=$this->translate("DELETE_CONFIRM_TEXT");?> &laquo;<?=$termcategory->getName()?>&raquo;</p>
                        <ul>
                            <li>
                                <a class='btn delete' href='<?=$this->url("admin", ['controller' => "termcategory", "action" => "delete", "id" => $termcategory->getId()])?>'><i class='fa fa-trash-o'></i><?=$this->translate("DELETE");?></a>
                            </li>
                            <li>
                                <a class='btn btn-default cancel'><i class='fa fa-times'></i><?=$this->translate("CANCEL");?></a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
<?php
        }
?>
    </div>
</section>