<section>
    <p>
        <a href="/admin/user" class="btn btn-default">
            <i class="fa fa-chevron-left"></i>&nbsp;<?=$this->session->BACK?>
        </a>
    </p>
    <div class='table-style'>
        <ul class="table-row">
            <li class="table-cell"><?=$this->session->NAME?></li>
            <li class="table-cell"><?=$this->lang->getName()?></li>
        </ul>
        <ul class="table-row">
          <li class="table-cell"><?=$this->session->ACTIVE?></li>
          <li class="table-cell"><? if ($this->lang->getActive()) { ?> <i class='fa fa-check'></i> <? } else {  ?> <i class='fa fa-times'></i> <?}?> </li>
        </ul>
    </div>
</section>