<section>
    <p>
        <a href="/admin/user" class="btn btn-default">
            <i class="fa fa-chevron-left"></i>&nbsp;<?=$this->translation->BACK;?>
        </a>
    </p>
    <div class='table-style'>
        <ul class="table-row">
            <li class="table-cell"><?=$this->translation->NAME;?></li>
            <li class="table-cell"><?=$this->lang->getName()?></li>
        </ul>
        <ul class="table-row">
          <li class="table-cell"><?=$this->translation->ACTIVE;?></li>
          <li class="table-cell"><?php if ($this->lang->getActive()) { ?> <i class='fa fa-check'></i> <?php } else {  ?> <i class='fa fa-times'></i> <?php } ?> </li>
        </ul>
    </div>
</section>