<div>
    <p>
        <a href="/admin/language" class="btn btn-default">
            <i class="fa fa-chevron-left"></i>&nbsp;<?=$this->translation->BACK?>
        </a>
    </p>
    <div class='form-inputs'>
    <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('admin',array('controller' =>'language','action' => 'modify','id' => $this->id)));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
    ?>
    </div>
</div>