<div class="jarviswidget jarviswidget-sortable jarviswidget-color-white" data-widget-deletebutton='false' data-widget-editbutton='false' data-widget-colorbutton='false'>
<header>
  <span class="widget-icon"><i class="fa fa-list"></i></span>
  <h2>List of all content objects</h2>
</header>
<!-- widget div-->
<div>
<!-- widget content -->
  <div class="widget-body no-padding">
    <!-- <div class="widget-body-toolbar"></div> -->
  <!-- widget content -->
      <TABLE class="table table-striped table-bordered table-hover dataTable">
          <THEAD>
            <TR>
              <TH>ID</TH>
              <TH>title</TH>
              <TH>extract</TH>
              <TH>order</TH>
              <TH>date</TH>
              <TH>details</TH>
              <TH>modify</TH>
              <TH>delete</TH>
            </TR>
          </THEAD>
          <TBODY>
<?php
/* @var $item Admin\Model\Menu */
$menu = null;
/* @var $item Admin\Model\Content */
foreach($this->contents as $item)
{
    if($item->menu!=0 AND ($menu==null or $menu->id!=$item->menu))
    {
        $menu = $item->getMenuObject();
?>
<TR>
    <TH colspan="8"><b><?=$menu->caption?></b></TH>
</TR>
<?
    }
?>
<TR>
    <TD class='admin c'><?=$item->id?></TD>
    <TD class='admin'><?=$item->title?></TD>
    <TD class='admin'><?=substr(strip_tags($item->extract),0,200)?>...</TD>
    <TD class='admin'><?=$item->menuOrder?></TD>
    <TD class='admin'><?=$item->date?></TD>
    <TD class='admin c'>
    <a title='details' class='btn blue btn-default btn-sm' href='/admin/content/detail/id/<?=$item->id?>'><i class='fa fa-icon-fix fa-info'></i></a>
    </TD>
    <TD class='admin c'>
    <a title='Modify content object' href='/admin/content/modify/id/<?=$item->id?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
    </TD>
    <TD class='admin c'>
    <a id='delete_<?=$item->id?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
    <div style='display: none' id='delete_delete_<?=$item->id?>' class='dialog_hide'>
        <p>Are you sure you would like to delete this content?</p>
        <ul>
          <li><a class='btn btn-danger' href='/admin/content/delete/id/<?=$item->id?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
          <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
        </ul>
    </div>
    </TD>
</TR>
<?
}
// fetch all contents that have value content.menu=0 and type=0
if (sizeof($this->contentMenusWithoutMenu) > 0)
{
?>
  <tr class="c">
    <td colspan="8"><strong>Content menus with menu set to 0</strong></td>
  </tr>
<?
  foreach ($this->contentMenusWithoutMenu as $wm)
  {
?>
    <TR>
        <TD class='admin c'><?=$wm->id?></TD>
        <TD class='admin'><?=$wm->title?></TD>
        <TD class='admin'><?=substr(strip_tags($wm->extract),0,200)?>...</TD>
        <TD class='admin'><?=$wm->menuOrder?></TD>
        <TD class='admin'><?=$wm->date?></TD>
        <TD class='admin c'>
        <a title='details' class='btn blue btn-default btn-sm' href='/admin/content/detail/id/<?=$wm->id?>'><i class='fa fa-icon-fix fa-info'></i></a>
        </TD>
        <TD class='admin c'>
        <a title='Modify content object' href='/admin/content/modify/id/<?=$wm->id?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
        </TD>
        <TD class='admin c'>
        <a id='delete_<?=$wm->id?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
        <div style='display: none' id='delete_delete_<?=$wm->id?>' class='dialog_hide'>
            <p>Are you sure you would like to delete this content?</p>
            <ul>
              <li><a class='btn btn-danger' href='/admin/content/delete/id/<?=$wm->id?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
              <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
            </ul>
        </div>
        </TD>
    </TR>
<?
  }
}

if (sizeof($this->menuReport) > 0)
{
?>
  <tr class="c">
    <td colspan="8"><strong>Contents without menu (menu was deleted)</strong></td>
  </tr>
<?
  foreach ($this->menuReport as $cwm)
  {
?>
    <TR>
        <TD class='admin c'><?=$cwm->id?></TD>
        <TD class='admin'><?=$cwm->title?></TD>
        <TD class='admin'><?=substr(strip_tags($cwm->extract),0,200)?>...</TD>
        <TD class='admin'><?=$cwm->menuOrder?></TD>
        <TD class='admin'><?=$cwm->date?></TD>
        <TD class='admin c'>
        <a title='details' class='btn blue btn-default btn-sm' href='/admin/content/detail/id/<?=$cwm->id?>'><i class='fa fa-icon-fix fa-info'></i></a>
        </TD>
        <TD class='admin c'>
        <a title='Modify content object' href='/admin/content/modify/id/<?=$cwm->id?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
        </TD>
        <TD class='admin c'>
        <a id='delete_<?=$cwm->id?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
        <div style='display: none' id='delete_delete_<?=$cwm->id?>' class='dialog_hide'>
            <p>Are you sure you would like to delete this content?</p>
            <ul>
              <li><a class='btn btn-danger' href='/admin/content/delete/id/<?=$cwm->id?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
              <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
            </ul>
        </div>
        </TD>
    </TR>
<?
  }
}

// fetch all contents that have value content.menu=0 and type=1
if (sizeof($this->contentNewsWithoutMenu) > 0)
{
?>
  <tr class="c">
    <td colspan="8"><strong>Content news with menu set to 0</strong></td>
  </tr>
<?
  foreach ($this->contentNewsWithoutMenu as $wm2)
  {
?>
    <TR>
        <TD class='admin c'><?=$wm2->id?></TD>
        <TD class='admin'><?=$wm2->title?></TD>
        <TD class='admin'><?=substr(strip_tags($wm2->extract),0,200)?>...</TD>
        <TD class='admin'><?=$wm2->menuOrder?></TD>
        <TD class='admin'><?=$wm2->date?></TD>
        <TD class='admin c'>
        <a title='details' class='btn blue btn-default btn-sm' href='/admin/content/detail/id/<?=$wm2->id?>'><i class='fa fa-icon-fix fa-info'></i></a>
        </TD>
        <TD class='admin c'>
        <a title='Modify content object' href='/admin/content/modify/id/<?=$wm2->id?>' class='btn btn-default btn-sm orange'><i class='fa fa-icon-fix fa-pencil'></i></a>
        </TD>
        <TD class='admin c'>
        <a id='delete_<?=$wm2->id?>' href='#' class='btn btn-default btn-sm red delete dialog_delete' title='delete'><i class='fa fa-icon-fix fa-trash-o'></i></a>
        <div style='display: none' id='delete_delete_<?=$wm2->id?>' class='dialog_hide'>
            <p>Are you sure you would like to delete this content?</p>
            <ul>
              <li><a class='btn btn-danger' href='/admin/content/delete/id/<?=$wm2->id?>'><i class='fa fa-trash-o'></i>&nbsp; Delete</a></li>
              <li><a class='btn btn-default cancel'><i class='fa fa-times'></i>&nbsp; Cancel</a></li>
            </ul>
        </div>
        </TD>
    </TR>
<?
  }
}
?>
          </TBODY>
        </TABLE>
  </div>
  <!-- end widget content -->
</div>
</div>