<div>
    <a href="/admin/content" class="btn btn-labeled btn-default">
        <span class="btn-label"><i class="fa fa-chevron-left"></i></span><?=$this->translation->BACK;?>
    </a>
    <br/>
    <br/>
    <header>
        <span class="widget-icon"><i class="fa fa-list"></i></span>
        <h2>Modify content</h2>
    </header>
    <section class='well'>
        <?php
            $this->form->setAttribute('action', $this->url('admin',array('controller' =>'content','action' => 'modify','id' => $this->content->getId())));
            $this->form->prepare();
            echo $this->form()->openTag($this->form);
            echo $this->formCollection($this->form);
            echo $this->form()->closeTag();
        ?>
    </section>
</div>