<?php
if (count($this->contents) > 0)
{
    /*@var $c \Admin\Model\Content */
    foreach($this->contents as $c)
    {
        echo "<h2 itemprop='name'>".$c->getTitle()."</h2>";

        if($c->getPreview() != null)
        {
            $image = "/userfiles/preview/".$c->getPreview();
 ?>
            <figure>
                <a itemprop="url" href="<?=$image?>" id="news_image" title="<?=$c->getTitle();?>">
                    <img itemprop="image" src="<?=$image?>" title="<?=$c->getTitle();?>" alt="<?=$c->getTitle();?>" />
                </a>
            </figure>
<?php
        }
        if (!$this->hideMainMenu)
        {
            echo "<p itemprop='text' class='post-text'>".$c->getExtract()."</p>";
            if ($c->getText() != '')
            {
                echo "<p><a itemprop='url' class='read-more' href='index/page/id/{$c->id}'>{$this->translation->READ_MORE}</a></p>";
            }
        }
        else if ($this->hideMainMenu)
        {
            echo "<p itemprop='text' class='post-text'>".$c->getText()."</p>";
            $backMenuCaption = strtolower(str_replace(" ", "-", $c->getMenuObject()->getCaption()));
            echo "<p><a itemprop='url' class='read-more' href='/{$backMenuCaption}'>{$this->translation->BACK}</a></p>";
        }
    }
}
else
{
    echo "<h3 itemprop='name' class='c no-content'>".$this->translation->NO_CONTENT."</h3>";
}
?>